module.exports = [
  {
    type: 'radiogroup',
    messageKey: 'HourFormat',
    label: 'Time format',
    description: 'Choose 12-hour, 24-hour, or follow your phone\'s system setting.',
    group: 'tabTime',
    defaultValue: '0',
    options: [
      { label: 'System', value: '0' },
      { label: '12h', value: '1' },
      { label: '24h', value: '2' },
    ],
  },
  {
    type: 'radiogroup',
    messageKey: 'WeekStart',
    label: 'Week starts on',
    description: 'Sets which day appears first in the calendar columns.',
    group: 'tabTime',
    defaultValue: '0',
    options: [
      { label: 'Monday', value: '0' },
      { label: 'Sunday', value: '1' },
    ],
  },
  {
    type: 'radiogroup',
    messageKey: 'WeekNumberMode',
    label: 'Week number',
    description: 'ISO follows the international standard. Gregorian uses a simpler year-based count.',
    group: 'tabTime',
    defaultValue: '0',
    options: [
      { label: 'ISO', value: '0' },
      { label: 'Gregorian', value: '1' },
    ],
  },
  {
    type: 'radiogroup',
    messageKey: 'RealtimeSteps',
    label: 'Biometric updates',
    description: 'How often step count and heart rate are refreshed on the watch.',
    group: 'tabTime',
    defaultValue: '0',
    capabilities: ['HEALTH'],
    options: [
      { label: 'Optimised', value: '0' },
      { label: 'Every minute', value: '1' },
      { label: 'Live', value: '2' },
    ],
  },
  {
    type: 'radiogroup',
    messageKey: 'HeaderDisplay',
    label: 'Header',
    description: 'Choose what appears in the center of the top status bar.',
    group: 'tabDisplay',
    defaultValue: '0',
    options: [
      { label: 'Full date', value: '0' },
      { label: 'Step count', value: '1' },
      { label: 'Min/max temp', value: '2' },
      { label: 'Heart rate', value: '3' },
    ],
  },
  {
    type: 'radiogroup',
    messageKey: 'ClockFont',
    label: 'Clock font',
    description: 'Select the typeface used for the large time digits.',
    group: 'tabDisplay',
    defaultValue: '0',
    options: [
      { label: 'LECO', value: '0' },
      { label: 'Roboto', value: '1' },
      { label: 'Bitham Bold', value: '2' },
      { label: 'Bitham Medium', value: '3' },
    ],
  },
  {
    type: 'radiogroup',
    messageKey: 'BluetoothDisplay',
    label: 'Bluetooth icon',
    description: 'Control when the Bluetooth status icon is shown in the header.',
    group: 'tabDisplay',
    defaultValue: '1',
    options: [
      { label: 'Always', value: '0' },
      { label: 'When disconnected', value: '1' },
    ],
  },
  {
    type: 'radiogroup',
    messageKey: 'LocationMode',
    label: 'Location',
    description: 'Automatic uses GPS. Manual lets you enter a city name for weather.',
    group: 'tabWeather',
    defaultValue: '0',
    options: [
      { label: 'Automatic', value: '0' },
      { label: 'Manual', value: '1' },
    ],
  },
  {
    type: 'input',
    messageKey: 'ManualLocation',
    label: 'City name',
    description: 'Used when location is set to Manual. Enter a city, e.g. London.',
    group: 'tabWeather',
    defaultValue: '',
    attributes: {
      placeholder: 'e.g. London',
      limit: 48,
    },
  },
  {
    type: 'radiogroup',
    messageKey: 'ForecastHours',
    label: 'Forecast',
    description: 'How many hours of weather data to show on the watchface.',
    group: 'tabWeather',
    defaultValue: '24',
    options: [
      { label: '12h', value: '12' },
      { label: '24h', value: '24' },
      { label: '48h', value: '48' },
    ],
  },
  {
    type: 'toggle',
    messageKey: 'TemperatureDisplay',
    label: 'Feels-like temperature',
    description: 'When off, shows actual temperature. When on, shows feels-like values.',
    group: 'tabWeather',
    defaultValue: false,
  },
  {
    type: 'radiogroup',
    messageKey: 'TemperatureUnit',
    label: 'Temperature scale',
    description: 'Choose Celsius or Fahrenheit for all weather values.',
    group: 'tabWeather',
    defaultValue: '0',
    options: [
      { label: '°C', value: '0' },
      { label: '°F', value: '1' },
    ],
  },
  {
    type: 'toggle',
    messageKey: 'DebugMode',
    label: 'Debug mode',
    description: 'Enables developer options below for testing without real data.',
    group: 'tabDebug',
    defaultValue: false,
  },
  {
    type: 'toggle',
    messageKey: 'DemoWeather',
    label: 'Demo weather',
    description: 'Shows sample weather data instead of fetching from the network.',
    group: 'tabDebug',
    defaultValue: false,
  },
  {
    type: 'toggle',
    messageKey: 'DemoBiometrics',
    label: 'Demo biometrics',
    description: 'Shows sample step count and heart rate instead of live health data.',
    group: 'tabDebug',
    defaultValue: false,
    capabilities: ['HEALTH'],
  },
  {
    type: 'text',
    id: 'argus-footer',
    defaultValue: '',
  },
  {
    type: 'submit',
    defaultValue: 'Save Settings',
  },
];
