#!/usr/bin/env node
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.join(__dirname, '..');
var TOML_PATH = path.join(ROOT, 'release.toml');
var JS_PATH = path.join(ROOT, 'src', 'pkjs', 'release.js');
var PACKAGE_PATH = path.join(ROOT, 'package.json');

function parseReleaseToml(content) {
  var versionMatch = content.match(/^version\s*=\s*"([^"]+)"/m);
  if (!versionMatch) {
    throw new Error('release.toml: missing version = "x.y.z"');
  }

  var message = '';
  var multilineMatch = content.match(/^message\s*=\s*"""\r?\n([\s\S]*?)\r?\n"""/m);
  if (multilineMatch) {
    message = multilineMatch[1].replace(/\r\n/g, '\n');
  } else {
    var singleLineMatch = content.match(/^message\s*=\s*"((?:\\.|[^"\\])*)"/m);
    if (singleLineMatch) {
      message = singleLineMatch[1]
        .replace(/\\n/g, '\n')
        .replace(/\\t/g, '\t')
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, '\\');
    }
  }

  return {
    version: versionMatch[1],
    message: message.trim(),
  };
}

function jsStringLiteral(value) {
  return JSON.stringify(value);
}

function writeReleaseModule(release) {
  var module =
    '// Generated by scripts/generate-release.js — do not edit.\n' +
    'module.exports = {\n' +
    '  version: ' +
    jsStringLiteral(release.version) +
    ',\n' +
    '  message: ' +
    jsStringLiteral(release.message) +
    ',\n' +
    '};\n';

  fs.writeFileSync(JS_PATH, module, 'utf8');
}

function syncPackageVersion(version) {
  var pkg = JSON.parse(fs.readFileSync(PACKAGE_PATH, 'utf8'));
  if (pkg.version === version) {
    return;
  }
  pkg.version = version;
  fs.writeFileSync(PACKAGE_PATH, JSON.stringify(pkg, null, 2) + '\n', 'utf8');
}

function main() {
  var toml = fs.readFileSync(TOML_PATH, 'utf8');
  var release = parseReleaseToml(toml);
  writeReleaseModule(release);
  syncPackageVersion(release.version);
  console.log('Release ' + release.version + ' -> src/pkjs/release.js');
}

main();
